version: '3.5'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_PID: Express
      SA_PASSWORD: sa@123456
      ACCEPT_EULA: Y
      MSSQL_TCP_PORT: 1433 # Define the SQL Server port
    hostname : localhost
    ports:
      - "1450:1433"
    volumes:
      - ./db_scripts:/db_scripts


  tomcat-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - db-init
    environment:
      - DB_USERNAME=sa
      - DB_PASSWORD=sa@123456

      
  db-init:
    build:
      context: .
      dockerfile: init-db.Dockerfile
    depends_on:
      - sql-server