version: "3"

env:
  LOCAL_HOST: 8001
  M: "Update something"

tasks:
  dev:
    cmds:
      - uvicorn src:app --port {{.LOCAL_HOST}} --reload-dir src --log-level info

  config:
    cmds:
      - poetry config virtualenvs.in-project true

  updatedb:
    cmds:
      - alembic revision --autogenerate -m "{{.M}}"
