name: Auto-Tag Frontend Team

on:
  pull_request:
    types:
      - opened
      - synchronize
  issues:
    types:
      - opened
      - edited

jobs:
  auto_tag:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.FOR_TAG_FFOOD }}

    steps:
    - name: Check if the tag is 'frontend'
      id: check_tag
      run: |
        has_frontend_tag=$(echo ${{ github.event.issue.labels.*.name }} | awk '{print $NF}')
        if [[ "$has_frontend_tag" == "frontend" ]]; then
          echo "has_frontend_tag=1" >> $GITHUB_STATE
        else
          echo "has_frontend_tag=0" >> $GITHUB_STATE
        fi

    - name: Tag Frontend Team Members
      if: steps.check_tag.outputs.has_frontend_tag == '1'
      run: |
        # List of GitHub usernames of frontend team members
        FRONTEND_TEAM_MEMBERS="khengyun tien-thanh-hua HuynhVuGenius huynhkhachuy"

        for MEMBER in $FRONTEND_TEAM_MEMBERS; do
          gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees --method POST --field assignees[]=$MEMBER
        done
