name: Assign Frontend
on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened

jobs:
  assign_frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Assign Frontend
      if: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'frontend') }}
      run: |
        # List of assignees you want to assign
        assignees="khengyun,tien-thanh-hua,HuynhVuGenius,huynhkhachuy"
        IFS=',' read -ra assignees_array <<< "$assignees"

        for assignee in "${assignees_array[@]}"; do
          echo "Assigning $assignee to the pull request/issue..."
          gh issue assign --issue ${{ github.event.number }} --assignee $assignee
        done
